### ISSUE TITLE
Pytorch no londer supports this GPU because it is too old

### ISSUE THREAD

**Issue by ola-k-ase** [facebookresearch/demucs#116]
Hola, me aparece el siguiente error:
(demucs) C:\Users\Alien\demucs-master>python -m demucs.separate --dl -n demucs "C:\Users\Alien\Desktop\survive.mp3"
C:\Users\Alien\Anaconda3\envs\demucs\lib\site-packages\torch\cuda\__init__.py:135: UserWarning:
    Found GPU0 GeForce GTX 765M which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.
    The minimum cuda capability that we support is 3.5.

  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
Traceback (most recent call last):
  File "C:\Users\Alien\Anaconda3\envs\demucs\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Alien\Anaconda3\envs\demucs\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Alien\demucs-master\demucs\separate.py", line 143, in <module>
    main()
  File "C:\Users\Alien\demucs-master\demucs\separate.py", line 122, in main
    model = th.load(model_path).to(args.device)
  File "C:\Users\Alien\Anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 426, in to
    return self._apply(convert)
  File "C:\Users\Alien\Anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 202, in _apply
    module._apply(fn)
  File "C:\Users\Alien\Anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 202, in _apply
    module._apply(fn)
  File "C:\Users\Alien\Anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\rnn.py", line 123, in _apply
    ret = super(RNNBase, self)._apply(fn)
  File "C:\Users\Alien\Anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 224, in _apply
    param_applied = fn(param)
  File "C:\Users\Alien\Anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 424, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 314.00 MiB (GPU 0; 2.00 GiB total capacity; 1.43 GiB already allocated; 153.77 MiB free; 23.47 MiB cached)

¿Qué debo hacer?

**Comment by adefossez** [comment]
You should do the separation on CPU not GPU. For that run:
```bash
python -m demucs.separate -d cpu --dl -n demucs "C:\Users\Alien\Desktop\survive.mp3"
```

**Comment by ola-k-ase** [comment]
That solved my problem. Thanks.
