### ISSUE TITLE
OSError: libcudart.so.10.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by loretoparisi** [facebookresearch/demucs#225]
## 🐛 Bug Report

I get this error with latest Demux version:

```
Successfully built demucs
Installing collected packages: demucs
Successfully installed demucs-3.0.1
```

 and the Colab example notebook provided:

```
Going to separate the files:
/gdrive/MyDrive/demucs/82929740.mp3
With command:  python3 -m demucs.separate -o /gdrive/MyDrive/demucs_separated/ -n mdx_extra --mp3 --mp3-bitrate=320
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/demucs/separate.py", line 14, in <module>
    import torchaudio as ta
  File "/usr/local/lib/python3.7/dist-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import _extension  # noqa: F401
  File "/usr/local/lib/python3.7/dist-packages/torchaudio/_extension.py", line 27, in <module>
    _init_extension()
  File "/usr/local/lib/python3.7/dist-packages/torchaudio/_extension.py", line 21, in _init_extension
    torch.ops.load_library(path)
  File "/usr/local/lib/python3.7/dist-packages/torch/_ops.py", line 110, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.10.2: cannot open shared object file: No such file or directory
Command failed, something went wrong.
```

**Comment by adefossez** [comment]
Same issue https://github.com/facebookresearch/demucs/issues/225
It should be resolved now, sorry about that !

**Comment by loretoparisi** [comment]
Hello, it seems the problem still there on the main repo:

```
!pip install tqdm lameenc pyyaml
!pip install julius diffq dora-search
!pip install torchaudio openunmix
! git clone https://github.com/facebookresearch/demucs.git demucs
%cd demucs
! python setup.py install
...
```

and then same error on the Colab. Thank you!

**Comment by loretoparisi** [comment]
So the problem is not `torch` related:

```
import torch
print(torch.__version__)
1.10.0+cu111
```

but the offender module is `torchaudio`, that complains this cuda error:

```
import torchaudio
print(torchaudio.__version__)
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-10-10c67e7e79b4> in <module>()
----> 1 import torchaudio
      2 print(torchaudio.__version__)

4 frames
/usr/lib/python3.7/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    362 
    363         if handle is None:
--> 364             self._handle = _dlopen(self._name, mode)
    365         else:
    366             self._handle = handle

OSError: libcudart.so.10.2: cannot open shared object file: No such file or directory
```

**Comment by adefossez** [comment]
The colab is working for me now.  Are you sure you used the latest version of the colab ?
In my case it is quite clear that cuda version is cu111 from the pytorch version installed.
Maybe you are using colab pro ?

**Comment by loretoparisi** [comment]
@adefossez well in the notebook I remove the folder and then install again:
```
! rm -rf demucs
! git clone https://github.com/facebookresearch/demucs.git demucs
%cd demucs
! python setup.py install
```

so it's the latest.  I'm using normal Colab, but I had the same issue on Sagemaker Jupyter Notebook yesterday, before adding
```
%pip install torch==1.10.0+cu113 torchaudio==0.10.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
```

Maybe it was needed a kernel restart from scratch. That is possibile 👀

**Comment by adefossez** [comment]
This is super weird. On my colab cuda 111 is definitely used. So maybe I need a script to detect the cuda version and install the right pytorch.

**Comment by loretoparisi** [comment]
@adefossez Yes I think so, that would fix it. Closing for now, thanks.

**Comment by loretoparisi** [comment]
> This is super weird. On my colab cuda 111 is definitely used. So maybe I need a script to detect the cuda version and install the right pytorch.

@adefossez it seems that torchaudio is [now](https://github.com/googlecolab/colabtools/issues/2417) installed by defaults so I will try in a fresh kernel.

**Comment by adefossez** [comment]
that's amazing! good thing they fixed it upstream.
